<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/comment-list/template.latte */
final class Template_3b7a4a6ada extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div id="comment-list">
';
		foreach ($comments as $comment) /* pos 2:5 */ {
			echo '        ';
			echo LR\HtmlHelpers::escapeText(($this->global->fn->Comment)($this, $comment, $articleSlug)) /* pos 3:9 */;
			echo "\n";

		}

		echo '</div>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['comment' => '2'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
