<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/favorite-button/template.latte */
final class Template_39270e2747 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($compact) /* pos 1:9 */ {
			echo '<button class="btn btn-sm';
			echo LR\HtmlHelpers::escapeAttr($alignClass) /* pos 1:42 */;
			echo ' ';
			echo LR\HtmlHelpers::escapeAttr($buttonClass) /* pos 1:56 */;
			echo '"
        fx-action="/article/';
			echo LR\HtmlHelpers::escapeAttr($slug) /* pos 2:29 */;
			echo '/';
			echo LR\HtmlHelpers::escapeAttr($action) /* pos 2:37 */;
			echo LR\HtmlHelpers::escapeAttr($queryString) /* pos 2:46 */;
			echo '"
        fx-method="POST"
        fx-swap="outerHTML">
    <i class="ion-heart"></i> ';
			echo LR\HtmlHelpers::escapeText($count) /* pos 5:31 */;
			echo '
</button>
';
		}
		if (!$compact) /* pos 7:9 */ {
			echo '<button class="btn btn-sm';
			echo LR\HtmlHelpers::escapeAttr($alignClass) /* pos 7:43 */;
			echo ' ';
			echo LR\HtmlHelpers::escapeAttr($buttonClass) /* pos 7:57 */;
			echo '"
        fx-action="/article/';
			echo LR\HtmlHelpers::escapeAttr($slug) /* pos 8:29 */;
			echo '/';
			echo LR\HtmlHelpers::escapeAttr($action) /* pos 8:37 */;
			echo LR\HtmlHelpers::escapeAttr($queryString) /* pos 8:46 */;
			echo '"
        fx-method="POST"
        fx-swap="outerHTML">
    <i class="ion-heart"></i>
    &nbsp;
    ';
			echo LR\HtmlHelpers::escapeText($label) /* pos 13:5 */;
			echo ' Article <span class="counter">(';
			echo LR\HtmlHelpers::escapeText($count) /* pos 13:45 */;
			echo ')</span>
</button>
';
		}
	}
}
