<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/tag-list/template.latte */
final class Template_9f9b35b20d extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($variant === 'sidebar') /* pos 1:6 */ {
			echo '<div class="sidebar">
    <p>Popular Tags</p>
    <div class="tag-list">
';
			foreach ($tags as $tag) /* pos 4:12 */ {
				echo '        <a fx-yolo-deep href="/?tag=';
				echo LR\HtmlHelpers::escapeAttr($tag) /* pos 4:63 */;
				echo '" class="tag-pill tag-default">';
				echo LR\HtmlHelpers::escapeText($tag) /* pos 4:100 */;
				echo '</a>
';

			}

			echo '    </div>
</div>
';
		}
		if ($variant !== 'sidebar') /* pos 7:5 */ {
			echo '<ul class="tag-list">
';
			foreach ($tags as $tag) /* pos 8:9 */ {
				echo '    <li><a href="/?tag=';
				echo LR\HtmlHelpers::escapeAttr($tag) /* pos 8:50 */;
				echo '" class="tag-default tag-pill tag-outline">';
				echo LR\HtmlHelpers::escapeText($tag) /* pos 8:99 */;
				echo '</a></li>
';

			}

			echo '</ul>
';
		}
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['tag' => '4, 8'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
