<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/feed-toggle/template.latte */
final class Template_ba18c3f266 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="feed-toggle">
    <ul class="nav nav-pills outline-active">
        <li class="nav-item">
';
		if ($isLoggedIn) /* pos 4:16 */ {
			echo '            <a fx-yolo-deep class="nav-link ';
			echo LR\HtmlHelpers::escapeAttr($activeFeed === 'your' ? 'active' : '') /* pos 4:64 */;
			echo '" href="/?feed=your">Your Feed</a>
';
		}
		if (!$isLoggedIn) /* pos 5:16 */ {
			echo '            <a fx-yolo-deep class="nav-link disabled" href="/login">Your Feed</a>
';
		}
		echo '        </li>
        <li class="nav-item">
            <a fx-yolo-deep class="nav-link ';
		echo LR\HtmlHelpers::escapeAttr($activeFeed === 'global' && !$activeTag ? 'active' : '') /* pos 8:45 */;
		echo '" href="/">Global Feed</a>
        </li>
';
		if ($activeTag) /* pos 10:13 */ {
			echo '        <li class="nav-item">
            <a fx-yolo-deep class="nav-link active" href="">#';
			echo LR\HtmlHelpers::escapeText($activeTag) /* pos 11:62 */;
			echo '</a>
        </li>
';
		}
		echo '    </ul>
</div>
';
	}
}
