<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/comment/template.latte */
final class Template_64fa1bf1a7 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="card" id="comment-';
		echo LR\HtmlHelpers::escapeAttr($id) /* pos 1:31 */;
		echo '">
    <div class="card-block">
        <p class="card-text">';
		echo LR\HtmlHelpers::escapeText($body) /* pos 3:30 */;
		echo '</p>
    </div>
    <div class="card-footer">
        <a href="/profile/';
		echo LR\HtmlHelpers::escapeAttr($authorUsername) /* pos 6:27 */;
		echo '" class="comment-author" title="Author Profile">
            <img';
		echo LR\HtmlHelpers::formatAttribute(' src', ($this->filters->checkUrl)($authorImageThumb)) /* pos 7:24 */;
		echo ' class="comment-author-img" width="32" height="32" alt="author avatar" />
        </a>
        &nbsp;
        <a href="/profile/';
		echo LR\HtmlHelpers::escapeAttr($authorUsername) /* pos 10:27 */;
		echo '" class="comment-author">
            ';
		echo LR\HtmlHelpers::escapeText($authorUsername) /* pos 11:13 */;
		echo '
        </a>
        <span class="date-posted">';
		echo LR\HtmlHelpers::escapeText($date) /* pos 13:35 */;
		echo '</span>
';
		if ($canDelete) /* pos 14:15 */ {
			echo '        <span class="mod-options">
            <i class="ion-trash-a"
               fx-action="/article/';
			echo LR\HtmlHelpers::escapeAttr($articleSlug) /* pos 16:36 */;
			echo '/comment/';
			echo LR\HtmlHelpers::escapeAttr($id) /* pos 16:59 */;
			echo '"
               fx-method="DELETE"
               fx-boost="false"
               fx-target="#comment-';
			echo LR\HtmlHelpers::escapeAttr($id) /* pos 19:36 */;
			echo '"
               fx-swap="outerHTML"></i>
        </span>
';
		}
		echo '    </div>
</div>
';
	}
}
