<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/article-meta/template.latte */
final class Template_54d9f88f8d extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<a href="/profile/';
		echo LR\HtmlHelpers::escapeAttr($authorUsername) /* pos 1:19 */;
		echo '" title="Author Profile">
    <img';
		echo LR\HtmlHelpers::formatAttribute(' src', ($this->filters->checkUrl)($authorImageThumb)) /* pos 2:16 */;
		echo ' width="32" height="32" alt="author avatar" />
</a>
<div class="info">
    <a href="/profile/';
		echo LR\HtmlHelpers::escapeAttr($authorUsername) /* pos 5:23 */;
		echo '" class="author">';
		echo LR\HtmlHelpers::escapeText($authorUsername) /* pos 5:57 */;
		echo '</a>
    <span class="date">';
		echo LR\HtmlHelpers::escapeText($date) /* pos 6:24 */;
		echo '</span>
</div>
';
	}
}
