<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/article-list/template.latte */
final class Template_b63303123a extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if (empty($articles)) /* pos 1:6 */ {
			echo '<div class="article-preview">
    ';
			echo LR\HtmlHelpers::escapeText($emptyMessage) /* pos 2:5 */;
			echo '
</div>
';
		}
		foreach ($articles as $article) /* pos 4:1 */ {
			echo '    ';
			echo LR\HtmlHelpers::escapeText(($this->global->fn->ArticlePreview)($this, $article)) /* pos 5:5 */;
			echo "\n";

		}
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['article' => '4'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
