<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/article-preview/template.latte */
final class Template_3969b12659 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="article-preview">
    <div class="article-meta" style="view-transition-name: ';
		echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeCss($slug)) /* pos 2:60 */;
		echo '-meta;">
        <a fx-yolo-deep href="/profile/';
		echo LR\HtmlHelpers::escapeAttr($authorUsername) /* pos 3:40 */;
		echo '" title="Author Profile">
            <img';
		echo LR\HtmlHelpers::formatAttribute(' src', ($this->filters->checkUrl)($authorImageThumb)) /* pos 4:24 */;
		echo ' width="32" height="32" alt="author avatar" />
        </a>
        <div class="info">
            <a fx-yolo-deep href="/profile/';
		echo LR\HtmlHelpers::escapeAttr($authorUsername) /* pos 7:44 */;
		echo '" class="author">';
		echo LR\HtmlHelpers::escapeText($authorUsername) /* pos 7:78 */;
		echo '</a>
            <span class="date">';
		echo LR\HtmlHelpers::escapeText($date) /* pos 8:32 */;
		echo '</span>
        </div>
        ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->FavoriteButton)($this, $article, $isFavorited, true, true)) /* pos 10:9 */;
		echo '
    </div>
    <a fx-yolo-deep href="/article/';
		echo LR\HtmlHelpers::escapeAttr($slug) /* pos 12:36 */;
		echo '" class="preview-link">
        <h1 style="view-transition-name: ';
		echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeCss($slug)) /* pos 13:42 */;
		echo '-title;">
            ';
		echo LR\HtmlHelpers::escapeText($title) /* pos 14:13 */;
		echo '
        </h1>
        <p>';
		echo LR\HtmlHelpers::escapeText($description) /* pos 16:12 */;
		echo '</p>
    </a>
    <div class="preview-footer">
        <a fx-yolo-deep href="/article/';
		echo LR\HtmlHelpers::escapeAttr($slug) /* pos 19:40 */;
		echo '" class="read-more">Read more...</a>
        <ul class="tag-list">
';
		foreach ($tagList as $tag) /* pos 21:17 */ {
			echo '            <li><a href="/?tag=';
			echo LR\HtmlHelpers::escapeAttr($tag) /* pos 21:61 */;
			echo '" class="tag-default tag-pill tag-outline">';
			echo LR\HtmlHelpers::escapeText($tag) /* pos 21:110 */;
			echo '</a></li>
';

		}

		echo '        </ul>
    </div>
</div>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['tag' => '21'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
