<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/user-info/template.latte */
final class Template_150daaba90 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="user-info">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-10 offset-md-1">
                <img';
		echo LR\HtmlHelpers::formatAttribute(' src', ($this->filters->checkUrl)($profile['image'] ?: '/img/smiley-cyrus.avif')) /* pos 5:28 */;
		echo ' class="user-img" alt="author avatar" />
                <h4>';
		echo LR\HtmlHelpers::escapeText($profile['username']) /* pos 6:21 */;
		echo '</h4>
                <p>';
		echo LR\HtmlHelpers::escapeText($profile['bio'] ?? '') /* pos 7:20 */;
		echo '</p>

';
		if ($isOwnProfile) /* pos 9:20 */ {
			echo '                <a href="/settings" class="btn btn-sm btn-outline-secondary action-btn">
                    <i class="ion-gear-a"></i>
                    &nbsp;
                    Edit Profile Settings
                </a>
';
		}
		echo '                ';
		if (!$isOwnProfile && $isLoggedIn) /* pos 14:17 */ {
			echo LR\HtmlHelpers::escapeText(($this->global->fn->FollowButton)($this, $profile, $isFollowing)) /* pos 14:51 */;
		}
		echo "\n";
		if (!$isOwnProfile && !$isLoggedIn) /* pos 15:20 */ {
			echo '                <a href="/login" class="btn btn-sm btn-outline-secondary action-btn">
                    <i class="ion-plus-round"></i>
                    &nbsp;
                    Follow ';
			echo LR\HtmlHelpers::escapeText($profile['username']) /* pos 18:28 */;
			echo '
                </a>
';
		}
		echo '            </div>
        </div>
    </div>
</div>
';
	}
}
