<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/tag-input/template.latte */
final class Template_3029bb1659 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<tag-input';
		echo LR\HtmlHelpers::formatAttribute(' name', $name) /* pos 1:19 */;
		echo LR\HtmlHelpers::formatAttribute(' value', $value) /* pos 1:35 */;
		echo '></tag-input>
';
	}
}
