<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/pagination/template.latte */
final class Template_506ac99bfc extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<nav>
    <ul class="pagination">
';
		if ($hasPrevious) /* pos 3:13 */ {
			echo '        <li class="page-item">
            <a fx-yolo-deep class="page-link"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)($previousUrl)) /* pos 4:54 */;
			echo '>Previous</a>
        </li>
';
		}
		if ($hasNext) /* pos 6:13 */ {
			echo '        <li class="page-item">
            <a fx-yolo-deep class="page-link"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)($nextUrl)) /* pos 7:54 */;
			echo '>Next</a>
        </li>
';
		}
		echo '    </ul>
</nav>
';
	}
}
