<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/article-actions/template.latte */
final class Template_85f78aeac2 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($isAuthor) /* pos 1:1 */ {
			echo '    <a class="btn btn-outline-secondary btn-sm" href="/editor/';
			echo LR\HtmlHelpers::escapeAttr($article['slug']) /* pos 2:63 */;
			echo '">
        <i class="ion-edit"></i> Edit Article
    </a>
    <form action="/article/';
			echo LR\HtmlHelpers::escapeAttr($article['slug']) /* pos 5:28 */;
			echo '/delete" method="POST" fx-boost="false" fx-confirm="Are you sure you want to delete this article?" style="display: inline;">
        <input type="hidden" name="csrf_token"';
			echo LR\HtmlHelpers::formatAttribute(' value', ($this->global->fn->csrf_token)($this, ));
			echo '>
        <button type="submit" class="btn btn-outline-danger btn-sm">
            <i class="ion-trash-a"></i> Delete Article
        </button>
    </form>
';
		} elseif ($isLoggedIn) /* pos 11:1 */ {
			echo '    ';
			echo LR\HtmlHelpers::escapeText(($this->global->fn->FollowButton)($this, ['username' => $article['author_username']], $isFollowing)) /* pos 12:5 */;
			echo '
    ';
			echo LR\HtmlHelpers::escapeText(($this->global->fn->FavoriteButton)($this, $article, $isFavorited)) /* pos 13:5 */;
			echo "\n";
		} else /* pos 14:1 */ {
			echo '    <a href="/login" class="btn btn-sm btn-outline-secondary">
        <i class="ion-plus-round"></i>
        &nbsp;
        Follow ';
			echo LR\HtmlHelpers::escapeText($article['author_username']) /* pos 18:16 */;
			echo '
    </a>
    <a href="/login" class="btn btn-sm btn-outline-primary">
        <i class="ion-heart"></i>
        &nbsp;
        Favorite Article <span class="counter">(';
			echo LR\HtmlHelpers::escapeText($favoritesCount) /* pos 23:49 */;
			echo ')</span>
    </a>
';
		}
	}
}
