<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/public/../components/banner/template.latte */
final class Template_045598d74a extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		echo '<div class="banner">
    <div class="container">
        <h1 class="logo-font">conduit</h1>
        <p>A place to share your knowledge.</p>
    </div>
</div>
';
	}
}
