<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/profile-tabs/template.latte */
final class Template_8ecc467c27 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="articles-toggle">
    <ul class="nav nav-pills outline-active">
        <li class="nav-item">
            <a class="nav-link ';
		echo LR\HtmlHelpers::escapeAttr($activeTab === 'my' ? 'active' : '') /* pos 4:32 */;
		echo '" href="/profile/';
		echo LR\HtmlHelpers::escapeAttr($username) /* pos 4:86 */;
		echo '?tab=my">My Articles</a>
        </li>
        <li class="nav-item">
            <a class="nav-link ';
		echo LR\HtmlHelpers::escapeAttr($activeTab === 'favorites' ? 'active' : '') /* pos 7:32 */;
		echo '" href="/profile/';
		echo LR\HtmlHelpers::escapeAttr($username) /* pos 7:93 */;
		echo '?tab=favorites">Favorited Articles</a>
        </li>
    </ul>
</div>
';
	}
}
