<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/comment-form/template.latte */
final class Template_89b637aa58 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<form class="card comment-form" fx-action="/article/';
		echo LR\HtmlHelpers::escapeAttr($articleSlug) /* pos 1:53 */;
		echo '/comments" fx-method="POST" fx-target="#comment-list" fx-swap="afterbegin" fx-reset>
    <div class="card-block">
        <textarea class="form-control" name="body" placeholder="Write a comment..." rows="3"></textarea>
    </div>
    <div class="card-footer">
        <img';
		echo LR\HtmlHelpers::formatAttribute(' src', ($this->filters->checkUrl)($userImage)) /* pos 6:20 */;
		echo ' class="comment-author-img" alt="author avatar" />
        <input type="hidden" name="csrf_token"';
		echo LR\HtmlHelpers::formatAttribute(' value', $csrfToken) /* pos 7:56 */;
		echo '>
        <button class="btn btn-sm btn-primary">
            Post Comment
        </button>
    </div>
</form>
';
	}
}
