<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/comment-form/template-guest.latte */
final class Template_34110bcf0a extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		echo '<p>
    <a href="/login">Sign in</a> or <a href="/register">sign up</a> to add comments on this article.
</p>
';
	}
}
