<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/footer/template.latte */
final class Template_b20f7ef443 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		echo '<footer>
    <div class="container">
        <a fx-yolo-deep href="/" class="logo-font">conduit</a>
        <span class="attribution">
            An interactive learning project from <a href="https://thinkster.io">Thinkster</a>. Code &amp; design licensed under MIT.
        </span>
        <ul class="nav navbar-nav pull-xs-right">
            <li class="nav-item">
                <a class="nav-link" href="https://github.com/JensRoland/realworld-ludicrous"><i class="ion-social-github"></i> Source code</a>
            </li>
        </ul>
    </div>
</footer>
';
	}
}
