<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/follow-button/template.latte */
final class Template_3c81538dec extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<button class="btn btn-sm btn-outline-secondary action-btn"
        fx-action="/profile/';
		echo LR\HtmlHelpers::escapeAttr($username) /* pos 2:29 */;
		echo '/';
		echo LR\HtmlHelpers::escapeAttr($action) /* pos 2:41 */;
		echo '"
        fx-method="POST"
        fx-swap="outerHTML">
    <i class="ion-plus-round"></i>
    &nbsp;
    ';
		echo LR\HtmlHelpers::escapeText($label) /* pos 7:5 */;
		echo ' ';
		echo LR\HtmlHelpers::escapeText($username) /* pos 7:14 */;
		echo '
</button>
';
	}
}
