<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/components/navbar/template.latte */
final class Template_a11369d547 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<nav class="navbar navbar-light">
    <div class="container">
        <a fx-yolo-deep class="navbar-brand" href="/">conduit</a>
        <ul class="nav navbar-nav pull-xs-right">
            <li class="nav-item">
                <a fx-yolo-deep class="nav-link';
		echo LR\HtmlHelpers::escapeAttr($currentPage === 'home' ? ' active' : '') /* pos 6:48 */;
		echo '" href="/">Home</a>
            </li>
';
		if ($isLoggedIn) /* pos 8:17 */ {
			echo '            <li class="nav-item">
                <a fx-yolo-deep class="nav-link';
			echo LR\HtmlHelpers::escapeAttr($currentPage === 'editor' ? ' active' : '') /* pos 9:48 */;
			echo '" href="/editor">
                    <i class="ion-compose"></i>&nbsp;New Article
                </a>
            </li>
';
		}
		if ($isLoggedIn) /* pos 13:17 */ {
			echo '            <li class="nav-item">
                <a fx-yolo-deep class="nav-link';
			echo LR\HtmlHelpers::escapeAttr($currentPage === 'settings' ? ' active' : '') /* pos 14:48 */;
			echo '" href="/settings">
                    <i class="ion-gear-a"></i>&nbsp;Settings
                </a>
            </li>
';
		}
		if ($isLoggedIn) /* pos 18:17 */ {
			echo '            <li class="nav-item">
                <a fx-yolo-deep class="nav-link';
			echo LR\HtmlHelpers::escapeAttr($currentPage === 'profile' ? ' active' : '') /* pos 19:48 */;
			echo '" href="/profile/';
			echo LR\HtmlHelpers::escapeAttr($currentUser['username']) /* pos 19:110 */;
			echo '" title="User Profile">
';
			if (!empty($currentUser['image'])) /* pos 20:26 */ {
				echo '                    <img';
				echo LR\HtmlHelpers::formatAttribute(' src', ($this->filters->checkUrl)($currentUser['image'])) /* pos 20:69 */;
				echo ' class="user-pic"';
				echo LR\HtmlHelpers::formatAttribute(' alt', $currentUser['username']) /* pos 20:116 */;
				echo '>
';
			}
			echo '                    ';
			echo LR\HtmlHelpers::escapeText($currentUser['username']) /* pos 21:21 */;
			echo '
                </a>
            </li>
';
		}
		if (!$isLoggedIn) /* pos 24:17 */ {
			echo '            <li class="nav-item">
                <a fx-yolo-deep class="nav-link';
			echo LR\HtmlHelpers::escapeAttr($currentPage === 'login' ? ' active' : '') /* pos 25:48 */;
			echo '" href="/login">Sign in</a>
            </li>
';
		}
		if (!$isLoggedIn) /* pos 27:17 */ {
			echo '            <li class="nav-item">
                <a fx-yolo-deep class="nav-link';
			echo LR\HtmlHelpers::escapeAttr($currentPage === 'register' ? ' active' : '') /* pos 28:48 */;
			echo '" href="/register">Sign up</a>
            </li>
';
		}
		echo '        </ul>
    </div>
</nav>
';
	}
}
