<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/public/../templates/settings.latte */
final class Template_5f800c1d0e extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="settings-page">
    <div class="container page">
        <div class="row">
            <div class="col-md-6 offset-md-3 col-xs-12">
                <h1 class="text-xs-center">Your Settings</h1>

                ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->ErrorMessages)($this, $error ?? null)) /* pos 7:17 */;
		echo '

                <form action="/settings" method="POST">
                    <fieldset>
                        <fieldset class="form-group">
                            <input class="form-control" type="text" name="image" placeholder="URL of profile picture"';
		echo LR\HtmlHelpers::formatAttribute(' value', $user['image'] ?? '') /* pos 12:127 */;
		echo '>
                        </fieldset>
                        <fieldset class="form-group">
                            <input class="form-control form-control-lg" type="text" name="username" placeholder="Your Name"';
		echo LR\HtmlHelpers::formatAttribute(' value', $user['username'] ?? '') /* pos 15:133 */;
		echo '>
                        </fieldset>
                        <fieldset class="form-group">
                            <textarea class="form-control form-control-lg" rows="8" name="bio" placeholder="Short bio about you">';
		echo LR\HtmlHelpers::escapeText($user['bio'] ?? '') /* pos 18:130 */;
		echo '</textarea>
                        </fieldset>
                        <fieldset class="form-group">
                            <input class="form-control form-control-lg" type="text" name="email" placeholder="Email"';
		echo LR\HtmlHelpers::formatAttribute(' value', $user['email'] ?? '') /* pos 21:126 */;
		echo '>
                        </fieldset>
                        <fieldset class="form-group">
                            <input class="form-control form-control-lg" type="password" name="password" placeholder="Password">
                        </fieldset>
                        <input type="hidden" name="csrf_token"';
		echo LR\HtmlHelpers::formatAttribute(' value', ($this->global->fn->csrf_token)($this, ));
		echo '>
                        <button class="btn btn-lg btn-primary pull-xs-right">
                            Update Settings
                        </button>
                    </fieldset>
                </form>
                <hr>
                <a href="/logout" class="btn btn-outline-danger">
                    Or click here to logout.
                </a>
            </div>
        </div>
    </div>
</div>
';
	}
}
