<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/public/../templates/login.latte */
final class Template_cb0a8d06f8 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="auth-page">
    <div class="container page">
        <div class="row">
            <div class="col-md-6 offset-md-3 col-xs-12">
                <h1 class="text-xs-center">Sign in</h1>
                <p class="text-xs-center">
                    <a href="/register">Need an account?</a>
                </p>

                ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->ErrorMessages)($this, $error ?? null)) /* pos 10:17 */;
		echo '

                <form action="/login" method="POST" fx-boost="false">
                    <fieldset class="form-group">
                        <input class="form-control form-control-lg" type="email" name="email" placeholder="Email" autocomplete="email" required>
                    </fieldset>
                    <fieldset class="form-group">
                        <input class="form-control form-control-lg" type="password" name="password" placeholder="Password" autocomplete="current-password" required>
                    </fieldset>
                    <input type="hidden" name="csrf_token"';
		echo LR\HtmlHelpers::formatAttribute(' value', ($this->global->fn->csrf_token)($this, ));
		echo '>
                    <button class="btn btn-lg btn-primary pull-xs-right">
                        Sign in
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
';
	}
}
