<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/public/../templates/layout.latte */
final class Template_7d0e075ef3 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="csrf-token"';
		echo LR\HtmlHelpers::formatAttribute(' content', ($this->global->fn->csrf_token)($this, ));
		echo '>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Conduit</title>
    <meta name="description" content="A place to share your knowledge.">
    <link rel="preload" href="/fonts/source-sans-pro-regular.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="/fonts/source-sans-pro-v22-latin-300.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="/fonts/source-sans-pro-v22-latin-600.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="/fonts/titillium-web-v17-latin-700.woff2" as="font" type="font/woff2" crossorigin>
';
		if ($currentPage === 'article') /* pos 13:11 */ {
			echo '    <link rel="preload" href="/fonts/source-serif-pro-regular.woff2" as="font" type="font/woff2" crossorigin>
';
		}
		if ($currentPage === 'article') /* pos 14:11 */ {
			echo '    <link rel="preload" href="/fonts/source-serif-pro-bold.woff2" as="font" type="font/woff2" crossorigin>
';
		}
		if ($currentPage === 'article') /* pos 15:11 */ {
			echo '    <link rel="preload" href="/fonts/source-sans-pro-v22-latin-700.woff2" as="font" type="font/woff2" crossorigin>
';
		}
		echo '    ';
		echo App\Lib\Vite::assets() /* pos 16:5 */;
		echo '
</head>
<body>
    ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->Navbar)($this, $currentPage)) /* pos 19:5 */;
		echo '

';
		$this->createTemplate((LR\Helpers::stringOrNull($ʟ_tmp = "{$content_template}.latte") ?? throw new InvalidArgumentException(sprintf('Template name must be a string, %s given.', get_debug_type($ʟ_tmp)))), $this->params, 'include')->renderToContentType('html') /* pos 21:5 */;
		echo '
    ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->Footer)($this, )) /* pos 23:5 */;
		echo '
    <script>
        // Inject CSRF token into all boosti requests
        document.addEventListener(\'fx:config\', (e) => {
            const token = document.querySelector(\'meta[name="csrf-token"]\')?.content;
            if (token) e.detail.cfg.headers[\'X-CSRF-Token\'] = token;
        });
    </script>
</body>
</html>
';
	}
}
