<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/public/../templates/profile.latte */
final class Template_16e39c189e extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="profile-page">
    ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->UserInfo)($this, $profile, $isFollowing ?? false)) /* pos 2:5 */;
		echo '

    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-10 offset-md-1">
                ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->ProfileTabs)($this, $profile['username'], $activeTab ?? 'my')) /* pos 7:17 */;
		echo '
                ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->ArticleList)($this, $articles)) /* pos 8:17 */;
		echo '
                ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->Pagination)($this, $page ?? 1, $limit ?? 20, $totalItems ?? 0, '/profile/' . $profile['username'], ['tab' => $activeTab ?? 'my'])) /* pos 9:17 */;
		echo '
            </div>
        </div>
    </div>
</div>
';
	}
}
