<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/public/../templates/article.latte */
final class Template_f4001b039d extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="article-page">
    <div class="banner">
        <div class="container">
            <h1 style="view-transition-name: ';
		echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeCss($article['slug'])) /* pos 4:46 */;
		echo '-title;">
                ';
		echo LR\HtmlHelpers::escapeText($article['title']) /* pos 5:17 */;
		echo '
            </h1>

            <div class="article-meta" style="view-transition-name: ';
		echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeCss($article['slug'])) /* pos 8:68 */;
		echo '-meta;">
                ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->ArticleMeta)($this, $article)) /* pos 9:17 */;
		echo '
                ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->ArticleActions)($this, $article, $isFavorited)) /* pos 10:17 */;
		echo '
            </div>
        </div>
    </div>

    <div class="container page">
        <div class="row article-content">
            <div class="col-md-12">
                ';
		echo $article['body_html'] /* pos 18:17 */;
		echo '
                ';
		if (!empty($article['tagList'])) /* pos 19:17 */ {
			echo LR\HtmlHelpers::escapeText(($this->global->fn->TagList)($this, $article['tagList'], 'inline')) /* pos 19:49 */;
		}
		echo '
            </div>
        </div>

        <hr />

        <div class="article-actions">
            <div class="article-meta">
                ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->ArticleMeta)($this, $article)) /* pos 27:17 */;
		echo '
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 col-md-8 offset-md-2">
                ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->CommentForm)($this, $article['slug'])) /* pos 33:17 */;
		echo '
                ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->CommentList)($this, $comments ?? [], $article['slug'])) /* pos 34:17 */;
		echo '
            </div>
        </div>
    </div>
</div>
';
	}
}
