<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/public/../templates/404.latte */
final class Template_a311bc9e2a extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		echo '<div class="container page">
    <div class="row">
        <div class="col-md-6 offset-md-3 col-xs-12">
            <h1 class="text-xs-center">Page Not Found</h1>
            <p class="text-xs-center">
                The page you\'re looking for doesn\'t exist.
                <a href="/">Go back home</a>
            </p>
        </div>
    </div>
</div>
';
	}
}
