<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/public/../templates/editor.latte */
final class Template_82a807c922 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="editor-page">
    <div class="container page">
        <div class="row">
            <div class="col-md-10 offset-md-1 col-xs-12">
                ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->ErrorMessages)($this, $error ?? null)) /* pos 5:17 */;
		echo '

                <form';
		echo LR\HtmlHelpers::formatAttribute(' action', ($this->filters->checkUrl)(isset($article) ? '/editor/' . $article['slug'] : '/editor')) /* pos 7:32 */;
		echo ' method="POST">
                    <fieldset>
                        <fieldset class="form-group">
                            <input type="text" class="form-control form-control-lg" name="title" placeholder="Article Title"';
		echo LR\HtmlHelpers::formatAttribute(' value', $article['title'] ?? '') /* pos 10:134 */;
		echo ' required>
                        </fieldset>
                        <fieldset class="form-group">
                            <input type="text" class="form-control" name="description" placeholder="What\'s this article about?"';
		echo LR\HtmlHelpers::formatAttribute(' value', $article['description'] ?? '') /* pos 13:137 */;
		echo ' required>
                        </fieldset>
                        <fieldset class="form-group">
                            <textarea class="form-control" rows="8" name="body" placeholder="Write your article (in markdown)" required>';
		echo LR\HtmlHelpers::escapeText($article['body'] ?? '') /* pos 16:137 */;
		echo '</textarea>
                        </fieldset>
                        <fieldset class="form-group">
                            <input type="text" class="form-control" name="tags" placeholder="Enter tags"';
		echo LR\HtmlHelpers::formatAttribute(' value', isset($article['tagList']) ? implode(',', $article['tagList']) : '') /* pos 19:114 */;
		echo '><div class="tag-list"></div>
                        </fieldset>
                        <input type="hidden" name="csrf_token"';
		echo LR\HtmlHelpers::formatAttribute(' value', ($this->global->fn->csrf_token)($this, ));
		echo '>
                        <button class="btn btn-lg pull-xs-right btn-primary" type="submit">
                            Publish Article
                        </button>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
';
	}
}
