<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /app/app/public/../templates/home.latte */
final class Template_ec16add81f extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="home-page">
    ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->Banner)($this, )) /* pos 2:5 */;
		echo '

    <div class="container page">
        <div class="row">
            <div class="col-md-9">
                ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->FeedToggle)($this, $activeFeed, $activeTag)) /* pos 7:17 */;
		echo '
                ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->ArticleList)($this, $articles)) /* pos 8:17 */;
		echo '
                ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->Pagination)($this, $offset, $limit, count($articles), '/', ['feed' => $activeFeed, 'tag' => $activeTag])) /* pos 9:17 */;
		echo '
            </div>

            <div class="col-md-3">
                ';
		echo LR\HtmlHelpers::escapeText(($this->global->fn->TagList)($this, $tags, 'sidebar')) /* pos 13:17 */;
		echo '
            </div>
        </div>
    </div>
</div>
';
	}
}
